"""Seed profiles. Every person is 21+. No real people."""

PROFILES = [
    {
        "id": "u01",
        "name": "Milo",
        "age": 28,
        "distance_km": 0.4,
        "online": True,
        "headline": "Coffee, then we'll see",
        "bio": "Designer. Weeknights only. No drama.",
        "tags": ["dates", "chat", "coffee"],
        "tribe": "otter",
        "city": "Heidelberg",
        "accent": "#7cb7ff",
    },
    {
        "id": "u02",
        "name": "Jonas",
        "age": 31,
        "distance_km": 1.1,
        "online": True,
        "headline": "Gym + kitchen",
        "bio": "Looking for regulars, not a roster.",
        "tags": ["gym", "nsa", "late"],
        "tribe": "jock",
        "city": "Heidelberg",
        "accent": "#8be0a4",
    },
    {
        "id": "u03",
        "name": "Armin",
        "age": 36,
        "distance_km": 2.3,
        "online": False,
        "headline": "Quiet nights",
        "bio": "Work in research. Prefer talking first.",
        "tags": ["dates", "talk", "discreet"],
        "tribe": "geek",
        "city": "Mannheim",
        "accent": "#c9b6ff",
    },
    {
        "id": "u04",
        "name": "Leo",
        "age": 24,
        "distance_km": 3.0,
        "online": True,
        "headline": "Visiting this week",
        "bio": "Here until Sunday. Show me a decent bar.",
        "tags": ["travel", "drinks", "fun"],
        "tribe": "twink",
        "city": "Heidelberg",
        "accent": "#ffb86b",
    },
    {
        "id": "u05",
        "name": "Sami",
        "age": 29,
        "distance_km": 4.6,
        "online": True,
        "headline": "Host / don't be weird",
        "bio": "Can host after 21. Be clear about what you want.",
        "tags": ["host", "nsa", "now"],
        "tribe": "bear",
        "city": "Weinheim",
        "accent": "#ff8fab",
    },
    {
        "id": "u06",
        "name": "Nico",
        "age": 33,
        "distance_km": 6.2,
        "online": False,
        "headline": "Friends first",
        "bio": "New in town. Looking for people, not a pitch.",
        "tags": ["friends", "chat", "dates"],
        "tribe": "mixed",
        "city": "Mannheim",
        "accent": "#7ad7f0",
    },
    {
        "id": "u07",
        "name": "Theo",
        "age": 41,
        "distance_km": 8.9,
        "online": True,
        "headline": "Older, not a mentor speech",
        "bio": "Direct messages only. If you want dad jokes, say so.",
        "tags": ["dates", "discreet", "host"],
        "tribe": "daddy",
        "city": "Karlsruhe",
        "accent": "#e6d37a",
    },
    {
        "id": "u08",
        "name": "Rafi",
        "age": 26,
        "distance_km": 12.4,
        "online": True,
        "headline": "Nightlife",
        "bio": "Bars > apps. Still here though.",
        "tags": ["nightlife", "fun", "chat"],
        "tribe": "circuit",
        "city": "Mannheim",
        "accent": "#9ae6b4",
    },
]

ME = {
    "id": "me",
    "name": "You",
    "age": 27,
    "headline": "Just looking around",
    "city": "Heidelberg",
    "online": True,
}
